/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca01.Interfaces;

/**
 *
 * @author Fernando
 */
public class MenuUsuario extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public MenuUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCadUsuario2 = new javax.swing.JButton();
        btnCadUsuario3 = new javax.swing.JButton();
        btnCadUsuario6 = new javax.swing.JButton();
        btnCadUsuario7 = new javax.swing.JButton();
        btnCadUsuario8 = new javax.swing.JButton();
        btnCadUsuario9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU");

        btnCadUsuario2.setBackground(new java.awt.Color(255, 0, 0));
        btnCadUsuario2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnCadUsuario2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca01/IMG/25376.png"))); // NOI18N
        btnCadUsuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadUsuario2ActionPerformed(evt);
            }
        });

        btnCadUsuario3.setBackground(new java.awt.Color(0, 255, 102));
        btnCadUsuario3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnCadUsuario3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca01/IMG/agenda.png"))); // NOI18N
        btnCadUsuario3.setText("Alugar");
        btnCadUsuario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadUsuario3ActionPerformed(evt);
            }
        });

        btnCadUsuario6.setBackground(new java.awt.Color(0, 255, 102));
        btnCadUsuario6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnCadUsuario6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca01/IMG/view-file.png"))); // NOI18N
        btnCadUsuario6.setText("Visualizar");
        btnCadUsuario6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadUsuario6ActionPerformed(evt);
            }
        });

        btnCadUsuario7.setBackground(new java.awt.Color(0, 255, 102));
        btnCadUsuario7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnCadUsuario7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca01/IMG/busca.png"))); // NOI18N
        btnCadUsuario7.setText("Busca de livro");
        btnCadUsuario7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadUsuario7ActionPerformed(evt);
            }
        });

        btnCadUsuario8.setBackground(new java.awt.Color(0, 255, 102));
        btnCadUsuario8.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnCadUsuario8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca01/IMG/return-book.png"))); // NOI18N
        btnCadUsuario8.setText("Devolver");
        btnCadUsuario8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadUsuario8ActionPerformed(evt);
            }
        });

        btnCadUsuario9.setBackground(new java.awt.Color(0, 255, 102));
        btnCadUsuario9.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnCadUsuario9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca01/IMG/Ícone-Carrinho-de-Compras-PNG.png"))); // NOI18N
        btnCadUsuario9.setText("Comprar");
        btnCadUsuario9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadUsuario9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)
                        .addComponent(btnCadUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCadUsuario7, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCadUsuario8, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCadUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCadUsuario9, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 40, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(btnCadUsuario6, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnCadUsuario6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadUsuario7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadUsuario8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadUsuario9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadUsuario2ActionPerformed
        // TODO add your handling code here:
        Principal principal=new Principal();
        principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCadUsuario2ActionPerformed

    private void btnCadUsuario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadUsuario3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadUsuario3ActionPerformed

    private void btnCadUsuario6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadUsuario6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadUsuario6ActionPerformed

    private void btnCadUsuario7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadUsuario7ActionPerformed
        // TODO add your handling code here:
        InterfaceBuscadelivro interfaceBuscadelivro=new InterfaceBuscadelivro();
        interfaceBuscadelivro.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCadUsuario7ActionPerformed

    private void btnCadUsuario8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadUsuario8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadUsuario8ActionPerformed

    private void btnCadUsuario9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadUsuario9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadUsuario9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadUsuario2;
    private javax.swing.JButton btnCadUsuario3;
    private javax.swing.JButton btnCadUsuario6;
    private javax.swing.JButton btnCadUsuario7;
    private javax.swing.JButton btnCadUsuario8;
    private javax.swing.JButton btnCadUsuario9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
